apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: go-ff-entity
  namespace: default
spec:
  runLatest:
    configuration:
      # TODO(shikanime): create a BuildTemplate for Bazel
      # build:
      #   apiVersion: build.knative.dev/v1alpha1
      #   kind: Build
      #   spec:
      #     template:
      #       name: bazel
      #       arguments:
      #       - name: IMAGE
      #         value: entity:latest
      #     timeout: 10m
      revisionTemplate:
        spec:
          container:
            image: entity:latest
            imagePullPolicy: Always
