version: "3"
services:
  broker:
    image: rabbitmq:3-alpine
    ports:
      - 5672:5672
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
  adminer:
    image: adminer:4-standalone
    ports:
      - 80:8080
  cache:
    image: mariadb:10.3
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 3306:3306
  deps:
    image: flyff-deps
    build:
      context: .
      dockerfile: deps.Dockerfile
  login:
    image: flyff
    depends_on:
      - deps
    build: .
    entrypoint: ./login
    ports:
      - 23000:23000
  cluster:
    image: flyff
    depends_on:
      - deps
    build: .
    entrypoint: ./cluster
    ports:
      - 28000:28000
  connection:
    image: flyff
    depends_on:
      - deps
    build: .
    entrypoint: ./connectionserver
    ports:
      - 5400:5400
  entity:
    image: flyff
    depends_on:
      - deps
    build: .
    entrypoint: ./entity
  chat:
    image: flyff
    depends_on:
      - deps
    build: .
    entrypoint: ./chat
  moving:
    image: flyff
    depends_on:
      - deps
    build: .
    entrypoint: ./moving
