version: "3"
services:
  broker:
    image: rabbitmq:3-alpine
    restart: on-failure
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - db-data:/var/lib/mysql
  adminer:
    image: adminer:4-standalone
    ports:
      - 8080:8080
    restart: on-failure
  cache:
    image: mariadb:10.3
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db
    restart: on-failure
  login:
    image: bazel/cmd/login:image
    environment:
      ENV_FILE: docker.env
    ports:
      - 23000:23000
    restart: on-failure
    volumes:
      - .:/go/src/go-ff/
  cluster:
    image: bazel/cmd/cluster:image
    environment:
      ENV_FILE: docker.env
    ports:
      - 28000:28000
    restart: on-failure
    volumes:
      - .:/go/src/go-ff/
  connectionserver:
    image: bazel/cmd/connectionserver:image
    environment:
      ENV_FILE: docker.env
    ports:
      - 5400:5400
    restart: on-failure
    volumes:
      - .:/go/src/go-ff/
  entity:
    image: bazel/cmd/entity:image
    environment:
      ENV_FILE: docker.env
    restart: on-failure
    volumes:
      - .:/go/src/go-ff/
  chat:
    image: bazel/cmd/chat:image
    environment:
      ENV_FILE: docker.env
    restart: on-failure
    volumes:
      - .:/go/src/go-ff/
  moving:
    image: bazel/cmd/moving:image
    environment:
      ENV_FILE: docker.env
    restart: on-failure
    volumes:
      - .:/go/src/go-ff/
  action:
    image: bazel/cmd/action:image
    environment:
      ENV_FILE: docker.env
    restart: on-failure
    volumes:
      - .:/go/src/go-ff/
volumes:
  db-data:
