apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
data:
  messageExpiration: "5000"
---
apiVersion: v1
kind: Secret
metadata:
  name: broker-credentials
type: Opaque
data:
  endpoint: YW1xcDovL3VzZXI6cFB2cVdVdW1VZkRYODVBRkhFa3dFbURoREt6MjVoa2pYRWpLYUNIVXVXSmNTVUpiYlR4czUyempCSmJoQGdvLWZmLWFtcXAtcmFiYml0bXE6NTY3Mg==
